In [1]:
!python -V

Python 3.9.16


In [3]:
import torch
print(torch.__version__)

2.0.1


In [29]:
from torchtext.datasets import WikiText2
train_iter = WikiText2(split='train')

In [30]:
from torchtext.data.utils import get_tokenizer
tokenizer = get_tokenizer('basic_english')

In [31]:
from torchtext.vocab import build_vocab_from_iterator
vocab = build_vocab_from_iterator(map(tokenizer, train_iter), specials=['<unk>'])

In [32]:
vocab.set_default_index(vocab['<unk>'])

In [33]:
train_iter, val_iter, test_iter = WikiText2()

In [43]:
dataitem = [item.strip() for item in train_iter]

In [44]:
dataitem

['',
 '= Valkyria Chronicles III =',
 '',
 'Senjō no Valkyria 3 : <unk> Chronicles ( Japanese : 戦場のヴァルキュリア3 , lit . Valkyria of the Battlefield 3 ) , commonly referred to as Valkyria Chronicles III outside Japan , is a tactical role @-@ playing video game developed by Sega and Media.Vision for the PlayStation Portable . Released in January 2011 in Japan , it is the third game in the Valkyria series . <unk> the same fusion of tactical and real @-@ time gameplay as its predecessors , the story runs parallel to the first game and follows the " Nameless " , a penal military unit serving the nation of Gallia during the Second Europan War who perform secret black operations and are pitted against the Imperial unit " <unk> Raven " .',
 "The game began development in 2010 , carrying over a large portion of the work done on Valkyria Chronicles II . While it retained the standard features of the series , it also underwent multiple adjustments , such as making the game more <unk> for series newco

In [45]:
newdataitem=[]
for item in dataitem:
            if item:
                    newdataitem.append(item)

In [46]:
len(newdataitem)

23767

In [48]:
data = [torch.tensor(vocab(tokenizer(item)), dtype=torch.long) for item in newdataitem]

In [49]:
len(data)

23767

In [50]:
data

[tensor([   9, 3849, 3869,  881,    9]),
 tensor([20000,    83,  3849,    88,     0,  3869,    21,   780, 28780,     2,
          6182,     3,  3849,     4,     1,  5023,    88,    20,     2,  1837,
          1018,     7,    14,  3849,  3869,   881,   629,   976,     2,    23,
             8,  5790,   299,    12,   575,   232,    67,   452,    19, 13722,
             5,   757,     3,  2500,    17,     1,  1767,  5637,     3,   155,
             6,   246,   354,     6,   976,     2,    24,    23,     1,   237,
            67,     6,     1,  3849,    93,     3,     0,     1,   156,  4419,
             4,  5790,     5,   729,    12,    58,  2096,    14,    43,  7075,
             2,     1,   333,  1085,  3218,     7,     1,    37,    67,     5,
          1694,     1, 11219,     2,     8, 19698,   313,  1063,  2082,     1,
          1702,     4, 19009,    56,     1,    95, 25357,   107,    52,  1938,
          1644,   288,   598,     5,    34, 13620,   120,     1,  2321,  1063,
           

: 

In [47]:
newdataitem

['= Valkyria Chronicles III =',
 'Senjō no Valkyria 3 : <unk> Chronicles ( Japanese : 戦場のヴァルキュリア3 , lit . Valkyria of the Battlefield 3 ) , commonly referred to as Valkyria Chronicles III outside Japan , is a tactical role @-@ playing video game developed by Sega and Media.Vision for the PlayStation Portable . Released in January 2011 in Japan , it is the third game in the Valkyria series . <unk> the same fusion of tactical and real @-@ time gameplay as its predecessors , the story runs parallel to the first game and follows the " Nameless " , a penal military unit serving the nation of Gallia during the Second Europan War who perform secret black operations and are pitted against the Imperial unit " <unk> Raven " .',
 "The game began development in 2010 , carrying over a large portion of the work done on Valkyria Chronicles II . While it retained the standard features of the series , it also underwent multiple adjustments , such as making the game more <unk> for series newcomers . Cha

In [35]:
"""Converts raw text into a flat Tensor."""
data = [torch.tensor(vocab(tokenizer(item)), dtype=torch.long) for item in train_iter]

c:\Users\lkk68\.conda\envs\mycondapy39\lib\site-packages\torch\utils\data\datapipes\iter\combining.py:297: UserWarning: Some child DataPipes are not exhausted when __iter__ is called. We are resetting the buffer and each child DataPipe will read from the start again.
  warnings.warn("Some child DataPipes are not exhausted when __iter__ is called. We are resetting "


In [36]:
data

[tensor([], dtype=torch.int64),
 tensor([   9, 3849, 3869,  881,    9]),
 tensor([], dtype=torch.int64),
 tensor([20000,    83,  3849,    88,     0,  3869,    21,   780, 28780,     2,
          6182,     3,  3849,     4,     1,  5023,    88,    20,     2,  1837,
          1018,     7,    14,  3849,  3869,   881,   629,   976,     2,    23,
             8,  5790,   299,    12,   575,   232,    67,   452,    19, 13722,
             5,   757,     3,  2500,    17,     1,  1767,  5637,     3,   155,
             6,   246,   354,     6,   976,     2,    24,    23,     1,   237,
            67,     6,     1,  3849,    93,     3,     0,     1,   156,  4419,
             4,  5790,     5,   729,    12,    58,  2096,    14,    43,  7075,
             2,     1,   333,  1085,  3218,     7,     1,    37,    67,     5,
          1694,     1, 11219,     2,     8, 19698,   313,  1063,  2082,     1,
          1702,     4, 19009,    56,     1,    95, 25357,   107,    52,  1938,
          1644,   288,   5

In [9]:
from torchtext.datasets import WikiText2
dataroot = '../data'
wikirain_iter = WikiText2(root=dataroot, split='train')

In [27]:
batch = next(iter(wikirain_iter))

In [26]:
batch

' \n'

In [16]:
for label, line in iter(wikirain_iter):
    print(label)
    print(line)
    break

In [2]:
# import datasets
from torchtext.datasets import IMDB

train_iter = IMDB(split='train')

In [6]:
train_iter

ShardingFilterIterDataPipe

In [8]:
def tokenize(label, line):
    return line.split()

tokens = []
for label, line in train_iter:
    print(label)
    print(line)
    break
    #tokens += tokenize(label, line)

c:\Users\lkk68\.conda\envs\mycondapy39\lib\site-packages\torch\utils\data\datapipes\iter\combining.py:297: UserWarning: Some child DataPipes are not exhausted when __iter__ is called. We are resetting the buffer and each child DataPipe will read from the start again.
  warnings.warn("Some child DataPipes are not exhausted when __iter__ is called. We are resetting "


KeyboardInterrupt: 

In [8]:
tokens

[]

In [3]:
dataroot = "/data/cmpe249-fa23/torchhome/"
from torchtext.datasets import WikiText2
wikirain_iter = WikiText2(root=dataroot, split='train')

In [22]:
next(iter(wikirain_iter))

' \n'

In [1]:
from torchtext.datasets import AG_NEWS

train_iter = iter(AG_NEWS(split="train"))

In [25]:

next(train_iter)


(3,
 'Iraq Halts Oil Exports from Main Southern Pipeline (Reuters) Reuters - Authorities have halted oil export\\flows from the main pipeline in southern Iraq after\\intelligence showed a rebel militia could strike\\infrastructure, an oil official said on Saturday.')